<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tname</name>
   <tag></tag>
   <elementGuidId>6b75560a-3dbc-4015-820f-f8292d3b030d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/modal-container/div/div/form/div[2]/form-input[2]/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/modal-container/div/div/form/div[2]/form-input[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
