<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month-Brand</name>
   <tag></tag>
   <elementGuidId>b29fe025-98ea-4745-8854-4d75d946a9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/modal-container/div/div/form/div[2]/form-input[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/modal-container/div/div/form/div[2]/form-input[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
