<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signin</name>
   <tag></tag>
   <elementGuidId>a97176c4-58a1-4504-9fb1-fe786c463ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/app-root/app-login/div/div/div/div/div/div/div/form/form-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/app-root/app-login/div/div/div/div/div/div/div/form/form-button/button</value>
   </webElementProperties>
</WebElementEntity>
