<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>9d8dd77e-0e00-4c2d-b2ba-9ac37e3b2913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/app-root/app-layout/div/div/div/div/app-employee-conf/div/div[3]/div/div/div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/app-root/app-layout/div/div/div/div/app-employee-conf/div/div[3]/div/div/div[2]/label/input</value>
   </webElementProperties>
</WebElementEntity>
