<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GBP</name>
   <tag></tag>
   <elementGuidId>34ffb06f-018a-4451-bc11-b8ff820ebe6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[3]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[3]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
