<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NOK</name>
   <tag></tag>
   <elementGuidId>dbfd5d72-6843-4a5f-bb1b-cf431a6d6573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[4]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[4]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
