<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEK</name>
   <tag></tag>
   <elementGuidId>000ff26a-4afd-4a25-aefe-01984e1690c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[5]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/modal-container/div/div/form/div[2]/table/tbody/tr[5]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
