<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employees</name>
   <tag></tag>
   <elementGuidId>5be33690-85d8-444b-8a8e-d42710ea5c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='left-side-menu-container']/ul/li[6]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='left-side-menu-container']/ul/li[6]/ul/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
